from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class VectorStore(Protocol):
    async def add(self, id: str, text: str, embedding: list[float], metadata: dict[str, Any] | None = None) -> None: ...
    async def search(self, embedding: list[float], top_k: int = 20, filter: dict[str, Any] | None = None) -> list[tuple[str, float, dict[str, Any]]]: ...
    async def delete(self, ids: list[str]) -> None: ...
    async def rebuild(self) -> None: ...
    async def close(self) -> None: ...
