from __future__ import annotations

from typing import Protocol, runtime_checkable

from ..types import Checkpoint, MemoryItem, Triplet


@runtime_checkable
class Storage(Protocol):
    # Resources
    async def save_resource(self, user_id: str, content: str) -> str: ...
    async def get_resource(self, resource_id: str) -> str | None: ...
    async def search_resources(self, user_id: str, query: str) -> list[str]: ...

    # Items
    async def save_item(self, item: MemoryItem) -> None: ...
    async def get_items(self, user_id: str, category: str | None = None, limit: int = 100) -> list[MemoryItem]: ...
    async def get_item_by_id(self, item_id: str) -> MemoryItem | None: ...
    async def search_items(self, user_id: str, query: str) -> list[MemoryItem]: ...
    async def update_item(self, item: MemoryItem) -> None: ...
    async def delete_items(self, item_ids: list[str]) -> None: ...
    async def get_items_older_than(self, user_id: str, days: int) -> list[MemoryItem]: ...
    async def get_items_not_accessed_since(self, user_id: str, days: int) -> list[MemoryItem]: ...
    async def get_high_access_items(self, user_id: str, min_count: int = 5) -> list[MemoryItem]: ...
    async def get_all_items(self, user_id: str) -> list[MemoryItem]: ...

    # Categories
    async def save_category(self, user_id: str, category: str, summary: str) -> None: ...
    async def load_category(self, user_id: str, category: str) -> str | None: ...
    async def list_categories(self, user_id: str) -> list[str]: ...

    # Checkpoints
    async def save_checkpoint(self, checkpoint: Checkpoint) -> None: ...
    async def get_latest_checkpoint(self, thread_id: str) -> Checkpoint | None: ...
    async def get_checkpoint_at_step(self, thread_id: str, step_id: str) -> Checkpoint | None: ...
    async def list_checkpoint_steps(self, thread_id: str) -> list[str]: ...

    # Triplets
    async def save_triplet(self, user_id: str, triplet: Triplet) -> None: ...
    async def get_triplets(self, user_id: str, subject: str | None = None) -> list[Triplet]: ...
    async def deactivate_triplet(self, user_id: str, subject: str, predicate: str) -> None: ...
    async def get_all_triplets(self, user_id: str) -> list[Triplet]: ...

    async def close(self) -> None: ...
